// Vial catalog — single source of truth for peptide vial sales
// Prices are per-vial, displayed to patients on the shop page
// Stripe sees all purchases as "Peptide Therapy" — itemized receipt sent separately via Resend

export const SHIPPING_OPTIONS = [
  { id: 'pickup_nb', label: 'Clinic Pickup — Newport Beach', price: 0 },
  { id: 'pickup_sc', label: 'Clinic Pickup — San Clemente', price: 0 },
  { id: 'overnight_ca', label: 'Overnight Shipping — California', price: 5000 },
  { id: 'overnight_national', label: 'Overnight Shipping — National', price: 7500 },
  { id: 'overnight_remote', label: 'Overnight Shipping — AK/HI/Remote', price: 10000 },
];

export const VIAL_CATEGORIES = [
  { id: 'recovery', label: 'Recovery' },
  { id: 'growth_hormone', label: 'Growth Hormone' },
  { id: 'longevity', label: 'Longevity & Specialty' },
  { id: 'neuro', label: 'Neuro & Sleep' },
  { id: 'immune', label: 'Immune' },
  { id: 'sexual_health', label: 'Sexual Health' },
];

export const VIAL_CATALOG = [
  // ── Recovery ──────────────────────────────────────────────
  {
    id: 'bpc157_tb4',
    name: 'BPC-157 / Thymosin Beta-4',
    subtitle: 'Recovery Blend',
    category: 'recovery',
    vialSize: '10mg / 10mg',
    dosage: '500mcg / 500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 33000,
    description: 'Accelerates tissue repair, reduces inflammation, and supports tendon, ligament, and gut healing.',
  },
  {
    id: 'recovery_4blend',
    name: 'Recovery 4-Blend',
    subtitle: 'KPV / BPC-157 / TB-500 / MGF',
    category: 'recovery',
    vialSize: '2mg KPV / 10mg BPC / 10mg TB / 1mg MGF',
    dosage: '100mcg / 500mcg / 500mcg / 50mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 33000,
    description: 'Enhanced recovery blend combining anti-inflammatory, tissue repair, and muscle growth factors.',
  },
  {
    id: 'bpc157_standalone',
    name: 'BPC-157',
    subtitle: 'Standalone',
    category: 'recovery',
    vialSize: '5mg',
    dosage: '250–500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: '10–20',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Targeted tissue repair peptide for gut healing, tendon recovery, and inflammation reduction.',
  },

  // ── Growth Hormone ────────────────────────────────────────
  {
    id: 'gh_2x',
    name: '2X Blend',
    subtitle: 'CJC-1295 / Ipamorelin',
    category: 'growth_hormone',
    vialSize: '5mg / 5mg',
    dosage: '500mcg / 500mcg per injection',
    frequency: '5 on / 2 off',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Growth hormone secretagogue blend for improved sleep, recovery, body composition, and anti-aging.',
  },
  {
    id: 'gh_3x',
    name: '3X Blend',
    subtitle: 'Tesamorelin / MGF / Ipamorelin',
    category: 'growth_hormone',
    vialSize: 'Varies by phase',
    dosage: '1.6mg starting dose',
    frequency: '5 on / 2 off',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Triple-action growth hormone blend targeting fat reduction, muscle growth, and deep recovery.',
  },
  {
    id: 'gh_4x',
    name: '4X Blend',
    subtitle: 'GHRP-2 / Tesamorelin / MGF / Ipamorelin',
    category: 'growth_hormone',
    vialSize: 'Varies by phase',
    dosage: '1.8mg starting dose',
    frequency: '5 on / 2 off',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Maximum-potency growth hormone blend for aggressive optimization of body composition and recovery.',
  },

  // ── Longevity & Specialty ─────────────────────────────────
  {
    id: 'nad_1000',
    name: 'NAD+',
    subtitle: 'Injection',
    category: 'longevity',
    vialSize: '1000mg',
    dosage: '50–200mg per injection',
    frequency: 'Daily or 2–3x weekly',
    injectionsPerVial: '5–20',
    reconstitution: 'Pre-reconstituted',
    priceCents: 50000,
    description: 'Cellular energy and DNA repair coenzyme. Supports mitochondrial function, brain health, and longevity.',
  },
  {
    id: 'motsc',
    name: 'MOTS-C',
    subtitle: 'Mitochondrial peptide',
    category: 'longevity',
    vialSize: '10mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily (5 on / 2 off) or 5mg every 5 days',
    injectionsPerVial: '2–10',
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Mitochondrial-derived peptide that enhances metabolism, insulin sensitivity, and exercise capacity.',
  },
  {
    id: 'ghk_cu',
    name: 'GHK-Cu',
    subtitle: 'Copper peptide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily',
    injectionsPerVial: '25–50',
    reconstitution: '3mL BAC water',
    priceCents: 16500,
    description: 'Copper-binding peptide for skin rejuvenation, collagen production, and tissue remodeling.',
  },
  {
    id: 'epithalon',
    name: 'Epithalon',
    subtitle: 'Telomere peptide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '10mg per injection',
    frequency: 'Daily x 20 days',
    injectionsPerVial: 5,
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Anti-aging peptide that activates telomerase to support telomere length and cellular longevity.',
  },
  {
    id: 'ss31',
    name: 'SS-31',
    subtitle: 'Elamipretide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily',
    injectionsPerVial: '25–50',
    reconstitution: '2mL BAC water',
    priceCents: 46200,
    description: 'Mitochondrial-targeted peptide that protects against oxidative damage and restores cellular energy.',
  },
  {
    id: 'aod9604',
    name: 'AOD-9604',
    subtitle: 'Fat loss peptide',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Modified growth hormone fragment that stimulates fat metabolism without affecting blood sugar or growth.',
  },
  {
    id: 'follistatin',
    name: 'Follistatin',
    subtitle: 'Myostatin inhibitor',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '200mcg per injection',
    frequency: 'Daily x 20 days',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 52800,
    description: 'Blocks myostatin to promote lean muscle growth and improve body composition.',
  },
  {
    id: 'hgh',
    name: 'HGH',
    subtitle: 'Human Growth Hormone',
    category: 'longevity',
    vialSize: '100iu',
    dosage: 'Provider-directed',
    frequency: 'Provider-directed',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 99000,
    description: 'Recombinant human growth hormone for provider-directed optimization protocols.',
  },
  {
    id: 'igf_lr3',
    name: 'IGF-LR3',
    subtitle: 'Growth factor',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '100–200mcg per injection',
    frequency: '5 on / 2 off',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Long-acting insulin-like growth factor for muscle growth, recovery, and tissue repair.',
  },

  // ── Neuro & Sleep ─────────────────────────────────────────
  {
    id: 'selank',
    name: 'Selank',
    subtitle: 'Anxiolytic peptide',
    category: 'neuro',
    vialSize: 'Standard vial',
    dosage: '250–500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 19800,
    description: 'Nootropic peptide that reduces anxiety, enhances focus, and modulates GABA and serotonin.',
  },
  {
    id: 'semax',
    name: 'Semax',
    subtitle: 'Cognitive peptide',
    category: 'neuro',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 19800,
    description: 'Neuroprotective peptide that enhances BDNF, improves memory, focus, and mental clarity.',
  },
  {
    id: 'dsip',
    name: 'DSIP',
    subtitle: 'Delta sleep-inducing peptide',
    category: 'neuro',
    vialSize: '10mg',
    dosage: '500mcg–1mg per injection',
    frequency: 'As needed before bed',
    injectionsPerVial: '10–20',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Natural sleep peptide that promotes deep, restorative delta-wave sleep without sedation.',
  },

  // ── Immune ────────────────────────────────────────────────
  {
    id: 'ta1',
    name: 'Thymosin Alpha-1',
    subtitle: 'TA1 — Immune modulator',
    category: 'immune',
    vialSize: 'Standard vial',
    dosage: '3–8mg per injection',
    frequency: '2x per week or when sick',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 36300,
    description: 'Thymic peptide that enhances T-cell function, natural killer cell activity, and immune surveillance.',
  },
  {
    id: 'ara290',
    name: 'ARA-290',
    subtitle: 'Neuroprotective',
    category: 'immune',
    vialSize: 'Standard vial',
    dosage: '1.6–4mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'EPO-derived peptide for neuroprotection, tissue repair, and reduction of chronic inflammation.',
  },

  // ── Sexual Health ─────────────────────────────────────────
  {
    id: 'pt141',
    name: 'PT-141',
    subtitle: 'Bremelanotide',
    category: 'sexual_health',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'As needed, 2 hours before activity',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Melanocortin receptor agonist that enhances sexual arousal and desire through central nervous system pathways.',
  },
];

export function getVialById(id) {
  return VIAL_CATALOG.find(v => v.id === id);
}

export function getVialsByCategory(categoryId) {
  return VIAL_CATALOG.filter(v => v.category === categoryId);
}

export function getShippingOption(id) {
  return SHIPPING_OPTIONS.find(s => s.id === id);
}
