// Vial catalog — single source of truth for peptide vial sales
// Prices are per-vial, displayed to patients on the shop page
// Stripe sees all purchases as "Peptide Therapy" — itemized receipt sent separately via Resend

export const SHIPPING_OPTIONS = [
  { id: 'pickup_nb', label: 'Clinic Pickup — Newport Beach', price: 0 },
  { id: 'pickup_sc', label: 'Clinic Pickup — San Clemente', price: 0 },
  { id: 'overnight_ca', label: 'Overnight Shipping — California', price: 5000 },
  { id: 'overnight_national', label: 'Overnight Shipping — National', price: 7500 },
  { id: 'overnight_remote', label: 'Overnight Shipping — AK/HI/Remote', price: 10000 },
];

export const VIAL_CATEGORIES = [
  { id: 'recovery', label: 'Recovery' },
  { id: 'growth_hormone', label: 'Growth Hormone' },
  { id: 'longevity', label: 'Longevity & Specialty' },
  { id: 'neuro', label: 'Neuro & Sleep' },
  { id: 'immune', label: 'Immune' },
  { id: 'sexual_health', label: 'Sexual Health' },
];

export const VIAL_CATALOG = [
  // ── Recovery ──────────────────────────────────────────────
  {
    id: 'bpc157_tb4',
    name: 'BPC-157 / Thymosin Beta-4',
    subtitle: 'Recovery Blend',
    category: 'recovery',
    vialSize: '10mg / 10mg',
    dosage: '500mcg / 500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 33000,
    description: 'Accelerates tissue repair, reduces inflammation, and supports tendon, ligament, and gut healing.',
    benefits: ['Accelerates tendon, ligament, and muscle repair', 'Reduces systemic and localized inflammation', 'Supports gut lining repair and digestive health', 'Promotes angiogenesis (new blood vessel formation)', 'Well-tolerated with minimal side effects'],
  },
  {
    id: 'recovery_4blend',
    name: 'Recovery 4-Blend',
    subtitle: 'KPV / BPC-157 / TB-500 / MGF',
    category: 'recovery',
    vialSize: '2mg KPV / 10mg BPC / 10mg TB / 1mg MGF',
    dosage: '100mcg / 500mcg / 500mcg / 50mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 33000,
    description: 'Enhanced recovery blend combining anti-inflammatory, tissue repair, and muscle growth factors.',
    benefits: ['Multi-pathway tissue repair and regeneration', 'KPV reduces inflammation at the cellular level', 'TB-500 promotes flexible tissue repair and mobility', 'MGF supports muscle growth and recovery from training', 'Combined synergy exceeds individual peptide effects'],
  },
  {
    id: 'klow',
    name: 'KLOW',
    subtitle: 'Recovery Blend',
    category: 'recovery',
    vialSize: 'Standard vial',
    dosage: 'Per protocol',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 40000,
    description: 'Recovery peptide blend for tissue repair, inflammation, and regeneration.',
    benefits: ['Comprehensive tissue repair from multiple peptide pathways', 'Reduces chronic and acute inflammation', 'Supports joint, tendon, and soft tissue recovery', 'Promotes faster healing after injury or surgery'],
  },
  {
    id: 'glow',
    name: 'GLOW',
    subtitle: 'GHK-Cu + Recovery Blend',
    category: 'recovery',
    vialSize: 'Standard vial',
    dosage: 'Per protocol',
    frequency: 'Daily',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 40000,
    description: 'Skin, hair, and recovery blend combining GHK-Cu with healing peptides.',
    benefits: ['Stimulates collagen and elastin production for skin quality', 'Supports hair thickness and growth', 'Promotes wound healing and tissue remodeling', 'Antioxidant protection at the cellular level', 'Combined skin rejuvenation and recovery benefits'],
  },
  {
    id: 'bpc157_standalone',
    name: 'BPC-157',
    subtitle: 'Standalone',
    category: 'recovery',
    vialSize: '5mg',
    dosage: '250–500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: '10–20',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Targeted tissue repair peptide for gut healing, tendon recovery, and inflammation reduction.',
    benefits: ['Targeted repair for tendons, ligaments, and muscles', 'Supports gut lining integrity and healing', 'Reduces localized inflammation', 'Promotes blood vessel formation in damaged tissue', 'Widely studied with a strong safety profile'],
  },

  // ── Growth Hormone ────────────────────────────────────────
  {
    id: 'gh_2x',
    name: '2X Blend',
    subtitle: 'CJC-1295 / Ipamorelin',
    category: 'growth_hormone',
    vialSize: '5mg / 5mg',
    dosage: '500mcg / 500mcg per injection',
    frequency: '5 on / 2 off',
    timing: '1 hour before dinner or 1 hour after dinner',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Growth hormone secretagogue blend for improved sleep, recovery, body composition, and anti-aging.',
    benefits: ['Stimulates natural growth hormone release', 'Improves deep sleep quality and recovery', 'Supports fat loss and lean body composition', 'Enhances skin elasticity and anti-aging effects', 'No suppression of natural GH production'],
  },
  {
    id: 'gh_2x_tesa',
    name: '2X Blend',
    subtitle: 'Tesamorelin / Ipamorelin',
    category: 'growth_hormone',
    vialSize: '5mg / 5mg',
    dosage: '500mcg / 500mcg per injection',
    frequency: '5 on / 2 off',
    timing: '1 hour before dinner or 1 hour after dinner',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Growth hormone secretagogue blend combining tesamorelin for targeted visceral fat reduction with ipamorelin for deep sleep, recovery, and anti-aging.',
    benefits: ['Tesamorelin targets visceral fat reduction specifically', 'Ipamorelin stimulates natural growth hormone release', 'Improves deep sleep quality and recovery', 'Supports fat loss and lean body composition', 'No suppression of natural GH production'],
  },
  {
    id: 'gh_3x',
    name: '3X Blend',
    subtitle: 'Tesamorelin / MGF / Ipamorelin',
    category: 'growth_hormone',
    vialSize: 'Varies by phase',
    dosage: '1.6mg starting dose',
    frequency: '5 on / 2 off',
    timing: '1 hour before dinner or 1 hour after dinner',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Triple-action growth hormone blend targeting fat reduction, muscle growth, and deep recovery.',
    benefits: ['Tesamorelin targets visceral fat reduction', 'MGF promotes muscle repair and growth', 'Ipamorelin supports deep sleep and recovery', 'Triple-pathway approach for body composition', 'Stronger GH pulse than single-peptide protocols'],
  },
  {
    id: 'gh_4x',
    name: '4X Blend',
    subtitle: 'GHRP-2 / Tesamorelin / MGF / Ipamorelin',
    category: 'growth_hormone',
    vialSize: 'Varies by phase',
    dosage: '1.8mg starting dose',
    frequency: '5 on / 2 off',
    timing: '1 hour before dinner or 1 hour after dinner',
    injectionsPerVial: 10,
    daysPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Maximum-potency growth hormone blend for aggressive optimization of body composition and recovery.',
    benefits: ['Maximum growth hormone stimulation from four peptides', 'Aggressive fat loss and body recomposition', 'GHRP-2 amplifies hunger signaling and GH release', 'Deep recovery and sleep optimization', 'Best suited for patients seeking maximum results'],
  },

  // ── Longevity & Specialty ─────────────────────────────────
  {
    id: 'nad_1000',
    name: 'NAD+',
    subtitle: 'Injection',
    category: 'longevity',
    vialSize: '1000mg',
    dosage: '100mg per injection (50 units on insulin syringe)',
    frequency: 'Daily or 2–3x weekly',
    injectionsPerVial: 10,
    reconstitution: '5mL BAC water — draw 50 units (0.5mL) for a 100mg injection, subQ',
    priceCents: 50000,
    description: 'Cellular energy and DNA repair coenzyme. Supports mitochondrial function, brain health, and longevity.',
    benefits: ['Boosts cellular energy and mitochondrial function', 'Supports DNA repair and cellular longevity', 'Enhances mental clarity and cognitive performance', 'Improves exercise recovery and endurance', 'Supports healthy aging at the cellular level'],
  },
  {
    id: 'motsc',
    name: 'MOTS-C',
    subtitle: 'Mitochondrial peptide',
    category: 'longevity',
    vialSize: '10mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily (5 on / 2 off) or 5mg every 5 days',
    injectionsPerVial: '2–10',
    reconstitution: '2mL BAC water',
    priceCents: 17500,
    description: 'Mitochondrial-derived peptide that enhances metabolism, insulin sensitivity, and exercise capacity.',
    benefits: ['Enhances metabolic function and insulin sensitivity', 'Improves exercise capacity and endurance', 'Supports healthy body composition and fat metabolism', 'Protects against age-related metabolic decline', 'Mitochondrial-derived with strong research backing'],
  },
  {
    id: 'ghk_cu',
    name: 'GHK-Cu',
    subtitle: 'Copper peptide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily',
    injectionsPerVial: '25–50',
    reconstitution: '3mL BAC water',
    priceCents: 16500,
    description: 'Copper-binding peptide for skin rejuvenation, collagen production, and tissue remodeling.',
    benefits: ['Stimulates collagen and elastin for firmer skin', 'Promotes hair growth and thickness', 'Accelerates wound healing and tissue remodeling', 'Powerful antioxidant and anti-inflammatory effects', 'Supports overall skin quality and complexion'],
  },
  {
    id: 'epithalon',
    name: 'Epithalon',
    subtitle: 'Telomere peptide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '10mg per injection',
    frequency: 'Daily x 20 days',
    injectionsPerVial: 5,
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Anti-aging peptide that activates telomerase to support telomere length and cellular longevity.',
    benefits: ['Activates telomerase to protect telomere length', 'Supports cellular longevity and healthy aging', 'Regulates melatonin for improved sleep quality', 'Antioxidant properties protect against DNA damage', 'Run in cycles for cumulative anti-aging benefits'],
  },
  {
    id: 'ss31',
    name: 'SS-31',
    subtitle: 'Elamipretide',
    category: 'longevity',
    vialSize: '50mg',
    dosage: '1–2mg per injection',
    frequency: 'Daily',
    injectionsPerVial: '25–50',
    reconstitution: '2mL BAC water',
    priceCents: 46200,
    description: 'Mitochondrial-targeted peptide that protects against oxidative damage and restores cellular energy.',
    benefits: ['Targets mitochondrial inner membrane directly', 'Restores cellular energy production', 'Protects against oxidative stress and damage', 'Supports heart, brain, and muscle function', 'Emerging research in age-related disease prevention'],
  },
  {
    id: 'aod9604',
    name: 'AOD-9604',
    subtitle: 'Fat loss peptide',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 30,
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Modified growth hormone fragment that stimulates fat metabolism without affecting blood sugar or growth.',
    benefits: ['Stimulates fat breakdown without affecting blood sugar', 'Does not promote bone or muscle growth (targeted fat loss)', 'No impact on appetite or insulin levels', 'Supports stubborn fat reduction in midsection', 'Well-tolerated with minimal side effects'],
  },
  {
    id: 'follistatin',
    name: 'Follistatin',
    subtitle: 'Myostatin inhibitor',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '200mcg per injection',
    frequency: 'Daily x 20 days',
    injectionsPerVial: 20,
    reconstitution: '2mL BAC water',
    priceCents: 52800,
    description: 'Blocks myostatin to promote lean muscle growth and improve body composition.',
    benefits: ['Inhibits myostatin to unlock muscle growth potential', 'Promotes lean muscle mass and strength', 'Supports body recomposition and fat reduction', 'Enhances exercise performance and recovery', 'Run in short cycles for best results'],
  },
  {
    id: 'igf_lr3',
    name: 'IGF-LR3',
    subtitle: 'Growth factor',
    category: 'longevity',
    vialSize: 'Standard vial',
    dosage: '100–200mcg per injection',
    frequency: '5 on / 2 off',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'Long-acting insulin-like growth factor for muscle growth, recovery, and tissue repair.',
    benefits: ['Promotes muscle hypertrophy and strength gains', 'Accelerates tissue repair and recovery', 'Longer half-life than standard IGF-1', 'Supports connective tissue and joint health', 'Best paired with training for maximum effect'],
  },

  // ── Neuro & Sleep ─────────────────────────────────────────
  {
    id: 'selank',
    name: 'Selank',
    subtitle: 'Anxiolytic peptide',
    category: 'neuro',
    vialSize: 'Standard vial',
    dosage: '250–500mcg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 19800,
    description: 'Nootropic peptide that reduces anxiety, enhances focus, and modulates GABA and serotonin.',
    benefits: ['Reduces anxiety without sedation or brain fog', 'Enhances focus and sustained attention', 'Modulates GABA and serotonin for stable mood', 'Supports BDNF expression for brain health', 'Non-habit-forming with no tolerance buildup'],
  },
  {
    id: 'semax',
    name: 'Semax',
    subtitle: 'Cognitive peptide',
    category: 'neuro',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 19800,
    description: 'Neuroprotective peptide that enhances BDNF, improves memory, focus, and mental clarity.',
    benefits: ['Boosts BDNF for enhanced neuroplasticity', 'Improves memory, focus, and mental clarity', 'Neuroprotective against stress and oxidative damage', 'Supports cognitive endurance during demanding work', 'Pairs well with Selank for comprehensive neuro support'],
  },
  {
    id: 'dsip',
    name: 'DSIP',
    subtitle: 'Delta sleep-inducing peptide',
    category: 'neuro',
    vialSize: '10mg',
    dosage: '500mcg–1mg per injection',
    frequency: 'As needed before bed',
    injectionsPerVial: '10–20',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Natural sleep peptide that promotes deep, restorative delta-wave sleep without sedation.',
    benefits: ['Promotes deep delta-wave restorative sleep', 'No sedation or morning grogginess', 'Helps regulate disrupted sleep patterns', 'Supports natural circadian rhythm', 'Use as-needed without dependency risk'],
  },

  // ── Immune ────────────────────────────────────────────────
  {
    id: 'ta1',
    name: 'Thymosin Alpha-1',
    subtitle: 'TA1 — Immune modulator',
    category: 'immune',
    vialSize: 'Standard vial',
    dosage: '3–8mg per injection',
    frequency: '2x per week or when sick',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 36300,
    description: 'Thymic peptide that enhances T-cell function, natural killer cell activity, and immune surveillance.',
    benefits: ['Enhances T-cell and natural killer cell function', 'Strengthens immune surveillance against infections', 'Supports recovery during illness or immune stress', 'Modulates immune response without overstimulation', 'FDA-approved internationally for immune support'],
  },
  {
    id: 'ara290',
    name: 'ARA-290',
    subtitle: 'Neuroprotective',
    category: 'immune',
    vialSize: 'Standard vial',
    dosage: '1.6–4mg per injection',
    frequency: 'Daily',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 29700,
    description: 'EPO-derived peptide for neuroprotection, tissue repair, and reduction of chronic inflammation.',
    benefits: ['Neuroprotective without erythropoietic effects', 'Reduces chronic systemic inflammation', 'Supports tissue repair and wound healing', 'Protects nerve function in neuropathy', 'Anti-inflammatory action through innate repair pathways'],
  },

  // ── Sexual Health ─────────────────────────────────────────
  {
    id: 'hcg',
    name: 'HCG',
    subtitle: 'Human chorionic gonadotropin',
    category: 'sexual_health',
    vialSize: '5,000 IU',
    dosage: '500 IU per injection',
    frequency: '2x per week',
    injectionsPerVial: 10,
    reconstitution: '2mL BAC water',
    priceCents: 22500,
    description: 'Supports natural testosterone production and fertility. 5,000 IU vial = 10 injections at 500 IU.',
    benefits: ['Maintains natural testosterone production during TRT', 'Supports fertility and testicular function', 'Prevents testicular atrophy on hormone therapy', 'Well-established safety profile with decades of use', 'Essential adjunct for men on testosterone replacement'],
  },
  {
    id: 'pt141',
    name: 'PT-141',
    subtitle: 'Bremelanotide',
    category: 'sexual_health',
    vialSize: 'Standard vial',
    dosage: '500mcg–1mg per injection',
    frequency: 'As needed, 2 hours before activity',
    injectionsPerVial: 'Varies',
    reconstitution: '2mL BAC water',
    priceCents: 13200,
    description: 'Melanocortin receptor agonist that enhances sexual arousal and desire through central nervous system pathways.',
    benefits: ['Enhances sexual desire and arousal centrally', 'Works through the nervous system, not vascular', 'Effective for both men and women', 'Use as-needed, not daily', 'FDA-approved active ingredient (Vyleesi)'],
  },
];

export function getVialById(id) {
  return VIAL_CATALOG.find(v => v.id === id);
}

export function getVialsByCategory(categoryId) {
  return VIAL_CATALOG.filter(v => v.category === categoryId);
}

export function getShippingOption(id) {
  return SHIPPING_OPTIONS.find(s => s.id === id);
}
